CarShop/ViewModels/CarListViewModel.cs
using CarShop.Data.Models;
using System.Collections.Generic;

namespace CarShop.ViewModels
{
    public class CarListViewModel
    {
        public IEnumerable<Car> GetAllCars { get; set; }

        public string CurrentCategory { get; set; }
    }
}

CarShop/ViewModels/HomeViewModel.cs
using CarShop.Data.Models;
using System.Collections.Generic;

namespace CarShop.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Car> FavouriteCars { get; set; }
    }
}

CarShop/ViewModels/ShopCartViewModel.cs
using CarShop.Data.Models;

namespace CarShop.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart ShopCart { get; set; }
    }
}

CarShop/Controllers/CarController.cs
using CarShop.Data.Interfaces;
using CarShop.Data.Models;
using CarShop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace CarShop.Controllers
{
    public class CarController : Controller
    {
        private readonly IAllCars __allCars;
        private readonly ICarCategory __allCategories;

        public CarController(IAllCars allCars, ICarCategory carCategory)
        {
            __allCars = allCars;
            __allCategories = carCategory;
        }

        [Route("Car/List")]
        [Route("Car/List/{category}")]
        public ViewResult List(string category)
        {
            IEnumerable<Car> cars = null;
            string currentCategory = string.Empty;
            if (string.IsNullOrEmpty(category))
            {
                cars = __allCars.Car.OrderBy(i => i.Id);
            }
            else
            {
                if (string.Equals("electro", category, StringComparison.OrdinalIgnoreCase))
                {
                    cars = __allCars.Car.Where(i => i.Category.CategoryName.Equals("Electrocar")).OrderBy(i => i.Id);
                    currentCategory = "Electrocar";
                }
                else
                {
                    cars = __allCars.Car.Where(i => i.Category.CategoryName.Equals("Classic cars")).OrderBy(i => i.Id);
                    currentCategory = "Classic cars";
                }
            }

            ViewBag.Title = "Page with automobiles";
            CarListViewModel carListViewModel = new CarListViewModel
            {
                GetAllCars = cars,
                CurrentCategory = currentCategory
            };

            return View(carListViewModel);
        }
    }
}

CarShop/Controllers/HomeController.cs
using CarShop.Data.Interfaces;
using CarShop.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CarShop.Controllers
{
    public class HomeController : Controller
    {
        private IAllCars _carRepository;

        public HomeController(IAllCars allCars)
        {
            _carRepository = allCars;
        }

        public ViewResult Index()
        {
            ViewBag.Title = "Car-Shop";
            var homeCars = new HomeViewModel
            {
                FavouriteCars = _carRepository.GetFavouriteCars
            };
            return View(homeCars);
        }
    }
}

CarShop/Controllers/OrderController.cs
using CarShop.Data.Interfaces;
using CarShop.Data.Models;
using Microsoft.AspNetCore.Mvc;

namespace CarShop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;

        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }

        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Chekout(Order order)
        {
            shopCart.ListShopItems = shopCart.GetShopItems();

            if (shopCart.ListShopItems.Count == 0)
            {
                ModelState.AddModelError(string.Empty, "The Cart is empty");
            }

            if (ModelState.IsValid)
            {
                allOrders.CreateOrder(order);
                return RedirectToAction("Complete");
            }

            return View();
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "The Car is ordered";
            return View();
        }
    }
}

CarShop/Controllers/ShopCartController.cs
using CarShop.Data.Interfaces;
using CarShop.Data.Models;
using CarShop.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace CarShop.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllCars _carRepository;
        private readonly ShopCart _shopCart;

        public ShopCartController(IAllCars carRepository, ShopCart shopCart)
        {
            _carRepository = carRepository;
            _shopCart = shopCart;
        }

        public ViewResult Index()
        {
            var items = _shopCart.GetShopItems();
            _shopCart.ListShopItems = items;

            var obj = new ShopCartViewModel
            {
                ShopCart = _shopCart
            };
            return View(obj);
        }

        public RedirectToActionResult AddToCart(int id)
        {
            var item = _carRepository.Car.FirstOrDefault(i => i.Id == id);
            if (item != null)
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }
    }
}

CarShop/Views/Car/List.cshtml
<h1>All Cars</h1>
<h3>@Model.CurrentCategory</h3>
<div class="row mt-5 mb-2">
    @{
        foreach (Car car in Model.GetAllCars)
            @Html.Partial("AllCars", car)
    }
</div>

CarShop/Views/Home/Index.cshtml
@model HomeViewModel

<h1>The best Automobiles</h1>
<div class="row mt-5 mb-2">
    @{
        foreach (Car car in Model.FavouriteCars)
            @Html.Partial("AllCars", car)
    }
</div>

CarShop/Views/Order/Checkout.cshtml
@model Order

<h3>Order</h3>
<div class="row mb-5">
    <form asp-action="Checkout" method="post" class="form-horizontal">
        <div class="form-group">
            <label asp-for="Name"></label>
            <div class="col-md-12">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Surname"></label>
            <div class="col-md-12">
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Adress"></label>
            <div class="col-md-12">
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Phone"></label>
            <div class="col-md-12">
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email"></label>
            <div class="col-md-12">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <input class="btn btn-success" type="submit" value="Finish order" />
    </form>
</div>

CarShop/Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

CarShop/Views/Shared/AllCars.cshtml
@model Car

    <div class="col-lg-4">
        <img class="img-thumbnail" src="@Model.Image" alt="@Model.Name" />
        <h2>@Model.Name</h2>
        <p>@Model.ShortDescription</p>
        <p>@Model.Price.ToString("c")</p>
        <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="AddToCart" asp-route-id="@Model.Id">Add to cart</a></p>
    </div>

CarShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <a class="navbar-brand">Car Shop</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Home </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Car/List/">All Cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Car/List/electro">Electrocars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Car/List/fuel">Classic Cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/ShopCart/">Cart</a>
                    </li>
                </ul>
                <form class="form-inline mt-2 mt-md-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container marketing">
        <div class=" container mt-5">
            @RenderBody()
        </div>
    </div>
    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>© 2020 Company, Inc. · <a href="#">Privacy</a> </p>
    </footer>
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>

CarShop/Views/ShopCart/Index.cshtml
@model ShopCartViewModel
<div class="container mt-5">
    @foreach (var el in Model.ShopCart.ListShopItems)
    {
        <div class="alert alert-warning mt-3">
            <p><b>Automobile:</b> @el.Car.Name</p>
            <p><b>Price:</b> @el.Car.Price.ToString("c")</p>
        </div>
    }
    <hr />
    <a class="btn btn-danger mb-5" asp-controller="Order" asp-action="Checkout">Buy</a>
</div>